github:
  is_project_page: false
theme: jekyll-theme-slate
title: Stephen Klatt, MPT
tagline: Stephen Klatt is a physiotherapist in Winnipeg, with a focus on treating acute and chronic pain. Call us to book an appointment today!
description: Winnipeg Physiotherapist
url: https://www.klattphysio.ca
author: Stephen Klatt
Twitter:
  username: KlattPhysio
  card: summary
  image: https://www.klattphysio.ca/android-chrome-384x384.png
  title: Stephen Klatt, MPT
social:
  name: KlattPhysio
  links:
    - https://twitter.com/KlattPhysio
    - https://www.linkedin.com/in/KlattPhysio
    - https://instagram.com/KlattPhysio

google_analytics: UA-163323223-1

#minima:
#  social_links:
 #   twitter: KlattPhysio
  #  instagram: KlattPhysio
  #  linkedin: klattphysio
    
   # youtube: KlattPhysio
   # youtube_channel: UCdhNII1iflCqr-avtbvD1iw
   # youtube_channel_name: KlattPhysio
