github:
  is_project_page: false
theme: jekyll-theme-slate
title: Stephen Klatt, MPT
tagline: Winnipeg Physiotherapist
description: Stephen Klatt is a Physiotherapist with a focus on treating acute and chronic pain. Located in the heart of Downtown Winnipeg on the corner of Broadway and Balmoral. 
url: https://www.klattphysio.ca
author: Stephen Klatt

twitter:
  username: KlattPhysio
  card: summary_large_image
  
logo: https://www.klattphysio.ca/android-chrome-384x384.png
social:
  name: KlattPhysio
  links:
    - https://twitter.com/KlattPhysio
    - https://www.linkedin.com/in/KlattPhysio
    - https://instagram.com/KlattPhysio

google_analytics: UA-163323223-1

include: ['_pages']

plugins:
  - jekyll-sitemap

#minima:
#  social_links:
 #   twitter: KlattPhysio
  #  instagram: KlattPhysio
  #  linkedin: klattphysio
    
   # youtube: KlattPhysio
   # youtube_channel: UCdhNII1iflCqr-avtbvD1iw
   # youtube_channel_name: KlattPhysio
